# UTF-8
server:
  servlet:
    encoding:
      charset: UTF-8
    session:
      timeout: 30m
      tracking-modes: cookie

# thymeleaf
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:file:./maindb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  web:
    resources:
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: /**